### ISSUE TITLE
Request RxLocation.settings().checkAndHandleResolution() analog

### ISSUE THREAD

**Issue by kosikov2006** [patloew/CoLocation#1]
Please, make analog for RxLocation.settings().checkAndHandleResolution()
I do not able to make a flow of CoLocations methods because of onActivityResult callback

**Comment by patloew** [comment]
The method used in the RxLocation library had issues with the case when the system kills the Activity. Also, the same applies when using the new `ActivityResultContract` API. Therefore I see no way to implement this in a way that is safe to use even when the system kills the Activity. I already provided a `sealed class SettingsResult` to simplify this, see the sample app.
