### ISSUE TITLE
PlayServices 21.0.1 - IncompatibleClassChangeError

### ISSUE THREAD

**Issue by jan-stoltman-bolt** [patloew/CoLocation#13]
Hi,
 
 When trying to update play-services-location from 20.0.0 to **21.0.1** I face an issue with IncompatibleClassChangeError coming from CoLocation. I included the exact error message below. I managed [to find an exact](https://github.com/mapbox/mapbox-navigation-android/issues/6613), although already solved, issue in Mapbox's issue tracker.
 
 ```
 java.lang.IncompatibleClassChangeError: 
 Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected
 (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in base.apk!classes35.dex)
    at com.patloew.colocation.CoLocationImpl$getLocationUpdates$1.invokeSuspend(CoLocationImpl.kt:111)
```

as well as 

```
 java.lang.IncompatibleClassChangeError:
 Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected 
 (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in base.apk!classes35.dex)
     at com.patloew.colocation.CoLocationImpl.getLastLocation(CoLocationImpl.kt:68)
```

This issue happens independently from Android, Coroutines, or other dependencies versions. It's also reproducible 100% of the time. 

Please let me know if I can assist with more information.

**Comment by patloew** [comment]
v1.1.1 should fix this, could you please check and report back? Thanks.

**Comment by jan-stoltman-bolt** [comment]
Looks good, thanks!
