### ISSUE TITLE
Release to mavenCentral

### ISSUE THREAD

**Issue by Jawnnypoo** [patloew/CoLocation#5]
This library is only available on jcenter, which is shutting down very soon

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

For now, you can get it on Jitpack

https://jitpack.io/#patloew/CoLocation/v1.0.0

But that might not be ideal for you.

**Comment by patloew** [comment]
I am in the process of migrating to maven central. Will update readme once it's done.

**Comment by patloew** [comment]
Version 1.0.0 is now available on Maven Central.

**Comment by Jawnnypoo** [comment]
Thanks for doing this!
